project:
  type: website
  render:
    - "*.md"
    - "*.qmd"

website:
  repo-url: "https://github.com/lsc-hubs/kenya-hub"
  repo-actions:
    - edit
    - issue
  page-footer:
    background: dark
    left:
    - text: <br/>LSC Hubs 2023
      file: https://www.lsc-hubs.org
  title: "Land Soil Crop Hub {{< var country >}}"
  navbar:
    background: white
    search: true
    left:
      - text: Data
        file: "/#data"
      - text: Maps
        file: "/#maps"
      - text: Use cases
        file: "/#use-cases"
      - text: Community
        file: "/#hub-community"
      - text: "Docs"
        file: "/#documentation"
  sidebar:
    - title: "Docs"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - text: User
          file: docs/user
        - text: Administrator
          file: docs/admin
        - section: Developer
          contents:
            - section: Hub components
              contents: docs/developer/*
            - section: Workshop Data
              contents: docs/developer/tutorial-data-management/*

format:
  html:
    page-layout: full
    theme:
      - ./assets/css/custom.scss
    code-copy: true
    code-overflow: wrap
