# the file gets loaded with env param QUARTO_PROFILE=rwanda or quarto render --profile rwanda

website:
  repo-url: "https://github.com/lsc-hubs/rwanda-hub"
  title: "Land Soil Crop Hub Rwanda"
  navbar:
    logo: ./assets/images/logo-rwanda.svg
    logo-alt: "Logo of Land Soil Crop Hub Rwanda"